### ISSUE TITLE
How do I use this repo to add new Javascript libraries to DNN?

### ISSUE THREAD

**Issue by ainsofsoo** [EngageSoftware/DNN-JavaScript-Libraries#28]

**Comment by bdukes** [comment]
I see your request in #27 to add _select2_.  Here are the steps I took to do that:

1. Clone the repository
2.  Call `.\NewBowerLibrary.ps1 select2` from PowerShell (passing the name of the package on [Bower](https://bower.io/))
3. I'm then prompted for the library's friendly name (in this case, it's just capitalized "Select2")
4. It opens the files for the new package
5. Enter the URL to the release notes and license
6. Update the `.dnn` manifest:
  - Fill in the description (based on the README on GitHub)
  - Fill in the CDN URL in the `.dnn` manifest
  - Uncomment the jQuery `dependency` in the `.dnn` manifest and set to the correct version
  - Look to see that there's a minified version of the JavaScript file, so replace `select2.js` with `select2.min.js` and update two references in the `.dnn` manifest
  - Since there are additional CSS files (beyond just the JavaScript file), I zipped those in a `Resources.zip` file and added `<component type="ResourceFile">` section that I copied from another library.
7. Commit to the Git repo
8. Push
